inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  # Exclude:
  # - "bin/**/*"
  # # Settings required to cache rubocop's results on Travis as well as locally.
  # # FIXME: disabled for now because we get fails in CI when it works locally, which we think
  # # are related to buggy caching. The CI run takes ~25s longer without caching, though.
  # UseCache: false
  # # CacheRootDirectory: $HOME/.cache
  # # AllowSymlinksInCacheRootDirectory: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Style/Encoding:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

Naming/MethodName:
  # there are methods named PATCH(), def self.Schema, ...
  Enabled: false

Lint/Debugger:
  Enabled: true

# it's hopeless ...
Metrics/LineLength:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: true

# Separating numbers by underscores to make them more readable (10_123_555 instead of 10123555) is nice but
# sometimes not desired; disabling this cop.
Style/NumericLiterals:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Style/CollectionMethods:
  # Mapping from undesired method to desired_method
  # e.g. to use `detect` over `find`:
  #
  # CollectionMethods:
  #   PreferredMethods:
  #     find: detect
  PreferredMethods:
    map: 'collect'
    map!: 'collect!'
    inject: 'reduce'
    detect: 'find'
    find_all: 'select'

Layout/TrailingWhitespace:
  Enabled: true

Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/AsciiComments:
Enabled: false

Style/CaseEquality:
  Enabled: true

Style/MultilineTernaryOperator:
  Enabled: true
