version: '2'

services:

  postgres:
    image: postgres:9.4.12-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

  redis:
    image: redis:3.2.9-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379"

  mongo:
    image: mongo:3.4.4
    ports:
      - "27017"

  core_test:
    build:
      context: .
      dockerfile: Dockerfile.develop
    depends_on:
      - postgres
      - redis
      - mongo
    env_file:
      - .env.docker
      - .env.test
