version: '3.1'


volumes:
  postgresdb:
    driver: local
  redisdb:
    driver: local
  mongodb:
    driver: local


services:

  core:
    build: .
    command: bundle exec puma -C config/puma.rb
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - mongo
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      SECRET_KEY_BASE: 4302a93016c91a2074f05c247570bd12a604c3368d711861df1cbab4b967d81796562097aad566f12016a721a6f461a1cd376a94f826721ab6fb8b483c5b8b81
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      MONGO_HOST: mongo
      HOSTNAME: http://localhost:3000
      ASSET_HOST: http://localhost:3000
      ATTR_ENCRYPTED_KEY: This is a salt for your soup
      REDIS_HOST: redis

  postgres:
    image: postgres:9.4
    ports:
      - "5432"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - postgresdb:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redisdb:/data
    ports:
      - "6379"

  mongo:
    image: mongo
    volumes:
      - mongodb:/data
    ports:
      - "27017"
