version: '3.1'


volumes:
  postgresdb:
    driver: local
  redisdb:
    driver: local
  mongodb:
    driver: local
  core_logs:
    driver: local

services:

  core:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - mongo
    environment:
      RAILS_ENV: production
      RACK_ENV: production
      SECRET_KEY_BASE: 4302a93016c91a2074f05c247570bd12a604c3368d711861df1cbab4b967d81796562097aad566f12016a721a6f461a1cd376a94f826721ab6fb8b483c5b8b81
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      MONGO_HOST: mongo
      HOSTNAME: http://localhost:3000
      ASSET_HOST: http://localhost:3000
      ATTR_ENCRYPTED_KEY: This is a salt for your soup
      REDIS_HOST: redis
    volumes:
      - .:/app
      - core_logs:/app/log

  postgres:
    image: postgres:9.4.12-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - postgresdb:/var/lib/postgresql/data

  redis:
    image: redis:3.2.9-alpine
    ports:
      - "6379"
    volumes:
      - redisdb:/data

  mongo:
    image: mongo:3.4.4
    ports:
      - "27017"
    volumes:
      - mongodb:/data
