version: '3.1'

volumes:
  postgresdb:
    driver: local
  redisdb:
    driver: local
  mongodb:
    driver: local

services:

  core:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - mongo
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      MONGO_HOST: mongo
  postgres:
    image: postgres:9.4
    ports:
      - "5432"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - postgresdb:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    volumes:
      - redisdb:/data
    ports:
      - "6379"

  mongo:
    image: mongo
    volumes:
      - mongodb:/data
    ports:
      - "27017"
