version: '3.1'


volumes:
  postgresdb:
    driver: local
  redisdb:
    driver: local
  mongodb:
    driver: local

services:

  core_web:
    build: .
    # command: rake db:init # this is a service for initilizing the seeds
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - mongo
    env_file: .env.docker

  core_worker:
    build: .
    command: bash -c "bundle exec rake db:migrate && bundle exec whenever --update-crontab && bundle exec sidekiq"
    depends_on:
      - postgres
      - redis
      - mongo
    env_file: .env.docker

  postgres:
    image: postgres:9.4.12-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - postgresdb:/var/lib/postgresql/data

  redis:
    image: redis:3.2.9-alpine
    ports:
      - "6379"
    volumes:
      - redisdb:/data

  mongo:
    image: mongo:3.4.4
    ports:
      - "27017"
    volumes:
      - mongodb:/data
