version: '3.1'

# These docker volumes will be persisted across invocations of docker-compose up.
# That means we don't have to initialize, migrate, etc. the database for every start of the containers.
volumes:
  postgresdb:
    driver: local
  redisdb:
    driver: local
  mongodb:
    driver: local

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
      - mongo
    env_file:
      - .env
      - .env.development
      - .env.development-docker
    volumes:
      # Mount the current directory into `/core` inside the running container.
      - '.:/core'

  postgres:
    image: postgres:9.6.5-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    volumes:
      - postgresdb:/var/lib/postgresql/data

  redis:
    image: redis:3.2.9-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379"
    volumes:
      - redisdb:/data

  mongo:
    image: mongo:3.4.4
    ports:
      - "27017"
    volumes:
      - mongodb:/data