source 'https://rubygems.org'

gem 'grape-swagger'
gem 'rails'
gem 'pg'
gem 'sinatra'
gem 'mongoid'
gem 'moped'
gem 'redis-rails'
gem 'redis-namespace'
gem 'bson'
gem 'puma'
gem 'haml-rails'
gem 'sass-rails'
gem 'coffee-rails'
gem 'coffee-script-source', '1.8.0' # TODO: https://github.com/jashkenas/coffeescript/issues/3829
gem 'uglifier'
gem 'rails_layout'
gem 'autoprefixer-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'select2-rails', '3.5.9.3'
gem 'inherited_resources',      github: 'josevalim/inherited_resources'  # TODO: remove inherited_resources
gem 'has_scope'
gem 'responders'
gem 'simple_form'
gem 'country_select'
gem 'cocoon'
gem 'active_link_to'
gem 'awesome_print'
gem 'mail_view'
gem 'devise'
gem 'devise_invitable'
gem 'devise-i18n'
gem 'devise-i18n-views'
gem 'grape'
gem 'jsonapi-resources',       github: 'cerebris/jsonapi-resources'
gem 'grape-jsonapi-resources', github: 'cdunn/grape-jsonapi-resources'
gem 'grape-swagger-rails',     github: 'mkristian/grape-swagger-rails', branch: 'oauth'
gem 'api-pagination'
gem 'rack-cors',               require: 'rack/cors'
gem 'hashie-forbidden_attributes'
gem 'doorkeeper'
gem 'rack-oauth2'
gem 'bcrypt'
gem 'rails-i18n'
gem 'authority'
gem 'sprockets-rails'
gem 'sprockets-es6'
gem 'rolify'
gem 'ffaker'
gem 'fabrication'
gem 'friendly_id'
gem 'metamagic'
gem 'immigrant'
gem 'mini_magick'
gem 'carrierwave'
gem 'carrierwave-base64'
gem 'fog'
gem 'aws-sdk'
gem 'aws-sdk-rails'
gem 'therubyracer'
gem 'draper', require: false
gem 'whenever', require: false
gem 'sidekiq'
gem 'sidekiq-limit_fetch'
gem 'faraday'
gem 'attribute_normalizer',       github: 'mdeering/attribute_normalizer'
gem 'geocoder'
gem 'jbuilder'
gem 'paper_trail'
gem 'money-rails'
gem 'wicked'
gem 'acts_as_commentable_with_threading'
gem 'awesome_nested_set'
gem 'acts-as-taggable-on'
gem 'remotipart', github: 'magicmarkker/remotipart'
gem 'public_activity'
gem 'gon'
gem 'tzinfo'
gem 'rails-timeago'
gem 'dependent-fields-rails'
gem 'ancestry'
gem 'attr_encrypted', '1.3.5'
gem 'sitemap_generator'
gem 'rack-google-analytics'
gem 'acts_as_list'
gem 'pusher'
gem 'gmaps4rails'
gem 'iban-tools'
gem 'highcharts-rails'
gem 'lograge'
gem 'cookie_alert'
gem 'devise-async'
gem 'omniauth-facebook'
gem 'koala'
gem 'byebug'
gem 'rails_autolink'
gem 'browser'
gem 'acts_as_votable', '~> 0.10.0'
gem 'i18n-tasks'
gem 'will_paginate', '~> 3.0.6'
gem 'high_voltage'
gem 'wine_bouncer', '~> 1.0'
gem 'multi_json', '~> 1.0'
gem 'oj', '~> 2.0'
gem 'oauth'
gem 'redis-mutex'

source 'http://rails-assets.org' do
  gem 'rails-assets-pace'
  gem 'rails-assets-resizeend'
  gem 'rails-assets-animate-css'
  gem 'rails-assets-font-awesome', '4.3.0'
  gem 'rails-assets-bootstrap'
  gem 'rails-assets-bootstrap-datepicker'
  gem 'rails-assets-bootstrap-select'
  gem 'rails-assets-sparklines'
  gem 'rails-assets-d3', '~> 4.2.0'
  gem 'rails-assets-fetch'
  gem 'rails-assets-switchery'
  gem 'rails-assets-underscore'
  gem 'rails-assets-jquery-readyselector'
  gem 'rails-assets-metisMenu'
  gem 'rails-assets-nanoscroller'
  gem 'rails-assets-fastclick'
  gem 'rails-assets-enquire'
  gem 'rails-assets-moment'
  gem 'rails-assets-dropzone'
  gem 'rails-assets-highcharts'
  gem 'rails-assets-bootstrap-tour'
  gem 'rails-assets-jquery-steps'
  gem 'rails-assets-jquery-validation'
  gem 'rails-assets-fancybox'
end

group :production, :staging do
  gem 'newrelic_rpm'
  gem 'asset_sync'
end

group :development, :test do
  gem 'brakeman', :require => false
  gem 'lol_dba'
  gem 'listen'
  gem 'launchy'
  gem 'guard'
  gem 'guard-livereload'
  gem 'guard-bundler'
  gem 'guard-brakeman'
end

group :development do
  gem 'pry-rails'
  gem 'bullet', github: 'flyerhzm/bullet'
  gem 'rack-livereload'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'table_print'
  gem 'quiet_assets'
  gem 'annotate'
  gem 'yard'
end

group :test do
  gem 'vcr'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
  gem 'rspec-rails'
  gem 'email_spec'
  gem 'guard-rspec'
  gem 'database_cleaner'
  gem 'timecop'
  gem 'rspec-retry'
  gem 'webmock'
end
