source 'https://rubygems.org'

gem 'rails', '4.1.0.rc1'
gem 'mysql2'
gem 'mongoid', '~> 4.0.0.beta1', github: 'mongoid/mongoid'
gem 'bson', '~> 2.0.0.rc2'
gem 'unicorn-rails'
gem 'haml-rails'
gem 'sass-rails', '~> 4.0.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'rails_layout'
gem 'bootstrap-sass'
#gem 'designmodo-flatuipro-rails', '~> 1.2.5.0.branch'
gem 'font-awesome-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'jbuilder', '~> 1.2'
gem 'inherited_resources'
gem 'has_scope'
gem 'responders'
gem 'simple_form'
gem 'turbolinks'
gem 'awesome_print'
gem 'mail_view'
gem 'devise'
gem 'authority'
gem 'rolify'
gem 'ffaker'
gem 'highcharts-rails', '~> 3.0.0'
gem 'paloma'
gem 'fabrication'
gem 'friendly_id'
gem 'foreigner'
gem 'immigrant'
gem 'mini_magick'
gem 'carrierwave'
gem 'fog'
gem 'aws-sdk'
gem 'therubyracer'
gem 'draper'
gem 'whenever', :require => false
gem 'sidekiq'
gem 'faraday'


group :development do
  gem 'rack-mini-profiler'
  gem 'mailcatcher'
  gem 'brakeman', :require => false
  gem 'pry-rails'
  #gem 'bullet'
  gem 'rack-livereload'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'table_print'
end

group :development, :test do
  gem 'lol_dba'
  gem 'listen'
  gem 'launchy'
  gem 'growl'
  gem 'ruby_gntp'
  gem 'guard'
  gem 'guard-livereload'
  gem 'guard-bundler'
  gem 'guard-delayed'
end

group :test do
  gem 'guard-rspec'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'mocha'
  gem 'vcr', github: 'vcr/vcr'
  gem 'webmock'
  gem 'poltergeist'
  gem 'phantomjs'
  gem 'database_cleaner'
end