default: &default
  adapter: <%= ENV['DB_ADAPTER'] ||= 'postgresql' %>
  host: <%= ENV['DB_HOST'] ||= 'localhost' %>
  port: <%= ENV['DB_PORT'] ||= '5432' %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  encoding: unicode
  pool: 15
  checkout_timeout: 1
  reaping_frequency: 60

development:
  <<: *default
  database: buzzn_development

test:
  <<: *default
  database: buzzn_test

staging:
  <<: *default
  database: buzzn_staging

production:
  <<: *default
  database: buzzn_production
