default: &default
  adapter: <%= ENV['DB_ADAPTER'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  encoding: unicode
  pool: 16
  checkout_timeout: 0.5
  reaping_frequency: 60

development:
  <<: *default
  database: buzzn_development

test:
  <<: *default
  database: buzzn_test

staging:
  <<: *default
  database: buzzn_staging

production:
  <<: *default
  database: buzzn_production
