development:
  adapter: postgresql
  encoding: unicode
  database: buzzn_development
  pool: 25
  timeout: 1500

test:
  adapter: postgresql
  encoding: unicode
  database: buzzn_test
  pool: 25
  timeout: 1500
