development:
  adapter: mysql2
  host: localhost
  port: 8889
  database: buzzn_development
  username: root
  encoding: utf8

test:
  adapter: mysql2
  host: localhost
  port: 8889
  database: buzzn_test
  username: root
  encoding: utf8