default: &default
  adapter: postgresql
  encoding: unicode
  pool: 15
  checkout_timeout: 1
  reaping_frequency: 60
  username: postgres
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT'] || '5432' %>

development:
  <<: *default
  database: buzzn_development

test:
  <<: *default
  database: buzzn_test

staging:
  <<: *default
  database: buzzn_staging

production:
  <<: *default
  database: buzzn_production
