default: &default
  adapter: postgresql
  encoding: unicode
  pool: 15
  checkout_timeout: 1
  reaping_frequency: 60
  username: postgres
  host: <%= ENV['POSTGRES_HOST'] %>
  port: <%= ENV['POSTGRES_PORT'] %>


development:
  <<: *default
  database: buzzn_development

test:
  <<: *default
  database: buzzn_test

production:
  <<: *default
  database: buzzn_production
