en:
  errors:
    phone_number?: "must be a valid phone-number"

    iban?: "must be a valid iban"

    email?: "must be a valid email"

    url?: "must be a valid URL"

    has_owner_role?: "missing GROUP_OWNER role"

    metering_point_id?: 'missing metering_point_id'

    grid_consumption_group?: 'BUG: missing or wrong register.meter.group'
    grid_feeding_group?: 'BUG: missing or wrong register.meter.group'
    grid_register_no_group?: 'BUG: grid register can not belong to group'

    distribution_system_operator?: 'wrong market function of distribution_system_operator'
    transmission_system_operator?: 'wrong market function of transmission_system_operator'
    electricity_supplier?: 'wrong market function of electricity_supplier'
    at_most_one_register_with_same_label?: 'must not have more than register with this label'

    localpool_owner?: 'must be the localpool owner'
    match_localpool?: 'meter.group must match contract.localpool'
    localpool_tariffs?: 'all tariff.group must match contract.localpool'
    cover_beginning_of_contract?: 'tariffs must cover beginning of contract'
    cover_ending_of_contract?: 'tariffs must cover end of contract'
    after?: 'must be after begin_date'
    not_in_future?: 'must not be in the future'
    single_substitute?: 'there can be only one substitute register per group'
    match_group?: 'BUG: group and deep nested group must match'
    lineup?: 'must line up'
    covers_beginning?: 'must cover begin date'
    covers_ending?: 'must cover end date'
    covers_ending?: 'must cover end date'
    inside_period?: 'must inside period'
    in_contract_tariffs?: 'must be in contract tariffs'
    belongs_to_contract?: 'must belong to contract'
    match_register?: 'must match register'
    grow_in_time?: 'must grow in time'