en:
  errors:
    valid_json?: "must be a valid JSON"

    phone_number?: "must be a valid phone-number"

    iban?: "must be a valid iban"

    bigint?: "must be an integer"

    email?: "must be a valid email"

    url?: "must be a valid URL"

    id?: "missing nested ID"

    has_owner_role?: "missing GROUP_OWNER role"

    metering_point_id?: 'missing metering_point_id'

    grid_consumption_group?: 'BUG: missing or wrong register.meter.group'
    grid_feeding_group?: 'BUG: missing or wrong register.meter.group'
    grid_register_no_group?: 'BUG: grid register can not belong to group'

    distribution_system_operator?: 'wrong market function of distribution_system_operator'
    transmission_system_operator?: 'wrong market function of transmission_system_operator'
    electricity_supplier?: 'wrong market function of electricity_supplier'
    at_most_one_register_with_same_label?: 'must not have more than register with this label'

    localpool_owner?: 'must be the localpool owner'
    match_localpool?: 'meter.group must match contract.localpool'
    localpool_tariffs?: 'all tariff.group must match contract.localpool'
    cover_beginning_of_contract?: 'tariffs must cover beginning of contract'
    after?: 'must be after begin_date'
    not_in_future?: 'must not be in the future'
    single_substitute?: 'there can be only one substitute register per group'
    match_group?: 'BUG: group and deep nested group must match'
    lineup?: 'must line up'
    covers_beginning?: 'must cover begin date'
    covers_ending?: 'must cover end date'
    inside_period?: 'must inside period'
    in_contract_tariffs?: 'must be in contract tariffs'
    belongs_to_contract?: 'must belong to contract'
    match_register?: 'must match register'
    grow_in_time?: 'must grow in time'
    mtype?: 'wrong type, must be %{type}'
    alphanumeric?: 'must be alphanumeric'
    only_active_contract: 'another contract is already active'
    no_other_billings_in_range: 'other billing items already exist'
    unique_begin_date?: 'duplicate begin dates present'
    are_complete_and_not_open?: 'billing_items are not complete and state is not open'
    value_is_lower_than?: 'begin_reading needs to be lower than end_reading'
    higher_than_previous?: 'reading must be higher than previous'
    each_after_begin_date?: 'must be after %{begin_date}'
    each_before_end_date?:  'must be before %{end_date}'
    all_registers_installed?: 'all registers must have a device_setup or change_meter_1 reading'
    begun_at?: 'localpool not active on begin_date'
