en:
  errors:
    valid_json?: 'must be a valid JSON' 

    phone_number?: 'must be a valid phone-number' 

    iban?: 'must be a valid iban' 

    bigint?: 'must be an integer' 

    email?: 'must be a valid email'

    url?: 'must be a valid URL' 

    id?: 'missing nested ID' 

    has_owner_role?: 'owner must have role GROUP_OWNER' 

    metering_point_id?: 'missing metering point id' 

    distribution_system_operator?: 'wrong market function of distribution system operator'
    transmission_system_operator?: 'wrong market function of transmission system operator' 
    electricity_supplier?: 'wrong market function of electricity supplier'
    at_most_one_register_with_same_label?: 'must not have more than one register with this label' 

    localpool_owner?: '%{person} must be the group owner' 
    localpool_tariffs?: 'tariffs must match group tariffs' 
    cover_beginning_of_contract?: 'tariffs must cover beginning of contract %{begin_date}' 
    after?: 'last date must be after begin date %{begin_date}' 
    not_in_future?: 'last date must not be in the future' 
    single_substitute?: 'there can be only one substitute register per group'
    match_group?: 'group and deep nested group must match' 
    lineup?: 'billing items must line up' 
    covers_beginning?: 'gap contract tariffs must cover begin date' 
    covers_ending?: 'must cover end date' 
    inside_period?: '%{item} must be inside time period'
    in_contract_tariffs?: 'tariff must be in contract tariffs' 
    belongs_to_contract?: 'register must belong to contract' 
    match_register?: 'must match register' 
    grow_in_time?: 'readings must grow in time' 
    mtype?: 'wrong type, must be %{type}' 
    alphanumeric?: 'must be alphanumeric' 
    only_active_contract: 'another contract is already active' 
    no_other_billings_in_range: 'other billing items already exist in this time range' 
    unique_begin_date?: 'duplicate begin dates present' 
    are_complete_and_not_open?: 'billing_items %{contact} are not complete and state is not open' 
    value_is_lower_than?: 'begin_reading needs to be lower than end_reading'
    higher_than_previous?: 'reading must be higher than previous reading' 
    lower_than_following?: 'reading must be lower than following reading' 
    each_after_begin_date?: 'all billing items must begin after %{begin_date}'
    each_before_end_date?:  'all billing items must end before %{end_date}' 
    all_registers_installed?: 'all registers must have a device_setup or change_meter_2 reading or similar'
    begun_at?: 'localpool not active on begin_date' 
    items_present: 'there must be at least one billing item present' 
    register_belongs_to_group: 'not all registers of that market location belong to that group' 
    no_calculated_billing?: 'reading is used in at least one calculated billing' 
    no_other_contract_in_range: 'there is already another contract in that time range present' 
    completeness: 'billing_items for billing with invoice number %{invoice_number} are not complete and state is not open' 
    active_localpool_processing_contract_at_begin?: 'there must be a processing contract for the group activ on begin date %{begin_date}' 
    upcoming_tariff_present?:  'There is no upcoming tariff present in the group which can be communicated to the powertakers.'
