en:
  errors:
    valid_json?: 'must be a valid JSON' #done

    phone_number?: 'must be a valid phone-number' #done

    iban?: 'must be a valid iban' #done

    bigint?: 'must be an integer' #done

    email?: 'must be a valid email' #done

    url?: 'must be a valid URL' #done

    id?: 'missing nested ID' #done

    has_owner_role?: 'owner must have role GROUP_OWNER' #done

    metering_point_id?: 'missing metering point id' #done

    distribution_system_operator?: 'wrong market function of distribution system operator' #done
    transmission_system_operator?: 'wrong market function of transmission system operator' #done
    electricity_supplier?: 'wrong market function of electricity supplier' #done
    at_most_one_register_with_same_label?: 'must not have more than one register with this label' #done

    localpool_owner?: '%{person} must be the group owner' #done
    localpool_tariffs?: 'tariffs must match group tariffs' #done
    cover_beginning_of_contract?: 'tariffs must cover beginning of contract %{begin_date}' #done
    after?: 'last date must be after begin date %{begin_date}' #done
    not_in_future?: 'last date must not be in the future' #done
    single_substitute?: 'there can be only one substitute register per group' #done
    match_group?: 'group and deep nested group must match' #done
    lineup?: 'billing items must line up' #done
    covers_beginning?: 'gap contract tariffs must cover begin date' #done
    covers_ending?: 'must cover end date' #done
    inside_period?: '%{item} must be inside time period' #done
    in_contract_tariffs?: 'tariff must be in contract tariffs' #done
    belongs_to_contract?: 'register must belong to contract' #done
    match_register?: 'must match register' #done
    grow_in_time?: 'readings must grow in time' #done
    mtype?: 'wrong type, must be %{type}' #done
    alphanumeric?: 'must be alphanumeric' #done
    only_active_contract: 'another contract is already active' #done
    no_other_billings_in_range: 'other billing items already exist in this time range' #done
    unique_begin_date?: 'duplicate begin dates present' #done
    are_complete_and_not_open?: 'billing_items %{contact} are not complete and state is not open' #done
    value_is_lower_than?: 'begin_reading needs to be lower than end_reading' #done
    higher_than_previous?: 'reading must be higher than previous reading' #done
    lower_than_following?: 'reading must be lower than following reading' #done
    each_after_begin_date?: 'all billing items must begin after %{begin_date}' #done
    each_before_end_date?:  'all billing items must end before %{end_date}' #done
    all_registers_installed?: 'all registers must have a device_setup or change_meter_2 reading or similar' #done
    begun_at?: 'localpool not active on begin_date' #done
    items_present: 'there must be at least one billing item present' #done
    register_belongs_to_group: 'not all registers of that market location belong to that group' #done
    no_calculated_billing?: 'reading is used in at least one calculated billing' #done
    no_other_contract_in_range: 'there is already another contract in that time range present' #done
    completeness: 'billing_items for billing with invoice number %{invoice_number} are not complete and state is not open' #done
    active_localpool_processing_contract_at_begin?: 'there must be a processing contract for the group activ on begin date %{begin_date}' #done
