development:
  clients:
    default:
      database: buzzn_development
      hosts:
        - <%= ENV['MONGO_HOST'] %>:27017
      options:
  options:
    preload_models: true

production:
  clients:
    default:
      database: buzzn_production
      hosts:
        - <%= ENV['MONGO_HOST'] %>:27017
      options:
  options:
    preload_models: true

test:
  clients:
    default:
      database: buzzn_test
      hosts:
        - <%= ENV['MONGO_HOST'] %>:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
