default: &default
  clients:
    default:
      database: buzzn
      hosts:
        - <%= ENV['MONGO_HOST'] %>:27017
      options:
  options:
    preload_models: true

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
