---
am-kindergarten: 
am-urtlgraben: '00000131'
bahnhofstr: '00000141'
bismarckstr: 
blumenthalstr: 
cerveteristrasse: 
cherubinistr: 
fritz-winter-strasse: '00000133'
gertrud-grunow-strasse: '00000134'
gotthardstrasse: 
haeberlstrasse: 
heigelstrasse: '00000143'
helbigstrasse: 
hoernleweg: '00000146'
hofackerstrasse: 
huehnefeldstrasse: 
karmensoeldnerstrasse: '00000130'
kaspar-spaeth-str: 
kopperpahler-allee: 
landsbergerstrasse: '00000142'
ligsalzstr: '00000154'
lindenstrasse: 
lissi-kaeser-strasse: '00000152'
loft: '00000140'
marktplatz: '00000145'
martinusstrasse: '00000144'
mehrgenerationenplatz-forstenried: 00000129
memminger-str: 
michaelisstrasse: '00000153'
nappenhorn: '00000163'
oberlaenderstrasse: 
orleansstrasse: 
panoramastrasse: 
pariser-strasse: 
prof-kurt-huber-str: 
reinmarplatz: '00000132'
ruhensdorf: 
ruth-drexel-str: 
scheffelstrasse: '00000137'
schweigerweg: 
soehren: 
sulz: 00000158
tassiloweg: 
ude: '00000157'
wachsbleiche: 
wagnis: 00000128
wagnisart-afrika: 00000139
wagnisart-australien-asien: '00000136'
wagnisart-europa-amerika: 00000138
waldstrasse: 00000198
woge: '00000135'
