---
am-kindergarten: 
am-urtlgraben: 00000109
bahnhofstr: '00000117'
bismarckstr: 
blumenthalstr: 
cerveteristrasse: 
cherubinistr: 
fritz-winter-strasse: '00000111'
gertrud-grunow-strasse: '00000112'
gotthardstrasse: 
haeberlstrasse: 
heigelstrasse: '00000106'
helbigstrasse: 
hoernleweg: 
hofackerstrasse: 
huehnefeldstrasse: 
karmensoeldnerstrasse: 00000108
kaspar-spaeth-str: 
kopperpahler-allee: 
landsbergerstrasse: 00000118
ligsalzstr: 
lindenstrasse: 
lissi-kaeser-strasse: 
loft: 
marktplatz: '00000122'
martinusstrasse: 00000119
mehrgenerationenplatz-forstenried: '00000120'
memminger-str: 
michaelisstrasse: 
oberlaenderstrasse: 
orleansstrasse: 
panoramastrasse: 
pariser-strasse: 
prof-kurt-huber-str: 
reinmarplatz: '00000110'
ruhensdorf: 
scheffelstrasse: 
schweigerweg: 
sulz: 
tassiloweg: 
ude: 
wachsbleiche: 
wagnis: '00000123'
wagnisart-afrika: '00000116'
wagnisart-australien-asien: '00000114'
wagnisart-europa-amerika: '00000115'
woge: '00000113'
