default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  hostname: <%= ENV["HOSTNAME"] %>
  asset_host: <%= ENV["ASSET_HOST"] %>
  aws_bucket: <%= ENV["AWS_BUCKET"] %>
  aws_access_key: <%= ENV["AWS_ACCESS_KEY"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_region: <%= ENV["AWS_REGION"] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
