# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: false
:concurrency: 20
:timeout: 30

development:
  :pidfile: tmp/pids/sidekiq.pid

staging:
  :pidfile: ../../shared/pids/sidekiq.pid

production:
  :pidfile: ../../shared/pids/sidekiq.pid

:logfile: log/sidekiq.log

:queues:
  - [high, 20]
  - [default, 10]
  - [low, 2]

:limits:
  low: 5

