# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: false
:concurrency: 25
:timeout: 30

development:
  :pidfile: tmp/pids/sidekiq.pid

staging:
  :pidfile: ../../shared/pids/sidekiq.pid

production:
  :pidfile: ../../shared/pids/sidekiq.pid

:logfile: log/sidekiq.log

:queues:
  - [high, 3]
  - [default, 2]
  - [low, 1]

:limits:
  low: 4

