# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:verbose: false
:concurrency: 10
:timeout: 30
:logfile: ./log/sidekiq.log
:queues:
  - ['high', 3]
  - ['default', 2]
  - ['low', 1]
:limits:
  default: 1
  low: 1

staging:
  pidfile: ../shared/pids/sidekiq.pid

production:
  pidfile: ../shared/pids/sidekiq.pid
