ready = ->
  # GENERATE RANDOM ALERT
  # =================================================================
  # Require Admin Core Javascript
  # http://themeon.net
  # =================================================================
  dataAlert = [
    {
      icon: 'fa fa-info fa-lg'
      title: 'Info'
      type: 'info'
    }
    {
      icon: 'fa fa-star fa-lg'
      title: 'Primary'
      type: 'primary'
    }
    {
      icon: 'fa fa-thumbs-up fa-lg'
      title: 'Success'
      type: 'success'
    }
    {
      icon: 'fa fa-bolt fa-lg'
      title: 'Warning'
      type: 'warning'
    }
    {
      icon: 'fa fa-times fa-lg'
      title: 'Danger'
      type: 'danger'
    }
    {
      icon: 'fa fa-leaf fa-lg'
      title: 'Mint'
      type: 'mint'
    }
    {
      icon: 'fa fa-shopping-cart fa-lg'
      title: 'Purple'
      type: 'purple'
    }
    {
      icon: 'fa fa-heart fa-lg'
      title: 'Pink'
      type: 'pink'
    }
    {
      icon: 'fa fa-sun-o fa-lg'
      title: 'Dark'
      type: 'dark'
    }
  ]
  # GROWL LIKE NOTIFICATIONS
  # =================================================================
  # Require Admin Core Javascript
  # =================================================================
  $('#demo-alert').on 'click', (ev) ->
    ev.preventDefault()
    dataNum = nifty.randomInt(0, 8)
    $.niftyNoty
      type: dataAlert[dataNum].type
      icon: dataAlert[dataNum].icon
      title: dataAlert[dataNum].title
      message: 'Lorem ipsum dolor sit amet.'
      container: 'floating'
      timer: 3500
    return
  # ALERT ON TOP PAGE
  # =================================================================
  # Require Admin Core Javascript
  # =================================================================
  # Show random page alerts.
  $('#demo-page-alert').on 'click', (ev) ->
    ev.preventDefault()
    dataNum = nifty.randomInt(0, 8)
    timer = do ->
      if nifty.randomInt(0, 5) < 4
        return 3000
      0
    # Show random page alerts.
    $.niftyNoty
      type: dataAlert[dataNum].type
      icon: dataAlert[dataNum].icon
      title: do ->
        if timer > 0
          return 'Autoclose Alert'
        'Sticky Alert Box'
      message: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.'
      timer: timer
    return
  # ASIDE
  # =================================================================
  # Toggle Visibe
  # =================================================================
  $('#demo-toggle-aside').on 'click', (ev) ->
    ev.preventDefault()
    if !nifty.container.hasClass('aside-in')
      $.niftyAside 'show'
      #asdVisCheckbox.niftyCheck 'toggleOn'
    else
      $.niftyAside 'hide'
      #asdVisCheckbox.niftyCheck 'toggleOff'
    return

  # ---
  # generated by js2coffee 2.0.0





$(document).ready(ready)










